{% set name = "sphinx-hoverxref" %}
{% set version = "1.2.0" %}
{% set sha256 = "d01a6d2d8d49d1f499926d45c7e3ca70d91d2ca7245ead58301102894cb28f7b" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - flit-core >=3.2,<4
    - pip
  run:
    - python >={{ python_min }}
    - sphinx >=1.8

test:
  imports:
    - hoverxref
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://pypi.org/project/sphinx-hoverxref/
  license: MIT
  license_file: LICENSE
  summary: A sphinx extension to show tooltips when hovering over a reference
  description: |
    sphinx-hoverxref is a Sphinx extension to add tooltips on cross references
    to documentation with the content of the linked section.
  dev_url: https://github.com/readthedocs/sphinx-hoverxref
  doc_url: https://sphinx-hoverxref.readthedocs.io/

extra:
  recipe-maintainers:
    - BSGalvan
