{% set name = "sphinx-hoverxref" %}
{% set version = "1.4.2" %}
{% set sha256 = "74fab961b1b8c0e9c2cf22fa195c0e783d635e78686d39dd06ff157c196ca0c9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - flit-core >=3.2,<4
    - pip
  run:
    - python >=3.8
    - sphinx >=1.8

test:
  imports:
    - hoverxref
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/sphinx-hoverxref/
  license: MIT
  license_file: LICENSE
  summary: A sphinx extension to show tooltips when hovering over a reference
  description: |
    sphinx-hoverxref is a Sphinx extension to add tooltips on cross references
    to documentation with the content of the linked section.
  dev_url: https://github.com/readthedocs/sphinx-hoverxref
  doc_url: https://sphinx-hoverxref.readthedocs.io/

extra:
  recipe-maintainers:
    - BSGalvan
